---
- hosts: all
  vars:
    http_port: 22
    max_clients: 200
  remote_user: ec2-user
  
  pre_tasks:
  - name: Gathering ec2 facts
    action: ec2_facts
  - name: Instance De-register
    local_action:
      module: ec2_elb
      instance_id: "{{ i-0ee4715ad28bf5cc7 }}"
      state: absent
  roles:
    - myrole
  
  task:
  
  - name: create text1
    shell: touch provanuova1.txt
  
    
  post_task:
  
  - name: Instance Register
    local_action:
      module: ec2_elb
      instance_id: "{{ i-0ee4715ad28bf5cc7 }}"
      ec2_elbs: "{{ item }}"
      state: present
    with_items: ec2_elbs
