---
- hosts: all
  vars:
    http_port: 22
    max_clients: 200
  remote_user: ec2-user
  tasks:
  - name: test connection
    ping:  
    
  - name: install ntp
    yum: name=ntp state=installed update_cache=yes

  - name: start ntp
    service: name=ntpd state=started
    
  - name: create text
    shell: state=touch prova.txt
    
  - name: create text2
    shell: state=touch prova2.txt
    
  - name: create text3
    shell: state=touch prova3.txt
    
  - name: create text4
    shell: state=touch prova4.html
    
  - name: create text5
    shell: state=touch prova5.yml
    
  
