---
- hosts: all
  vars:
    http_port: 22
    max_clients: 200
  remote_user: ec2-user
  tasks:
  - name: test connection
    ping:  
    
  - name: install ntp
    yum: name=ntp state=installed update_cache=yes

  - name: start ntp
    service: name=ntpd state=started
    
  
