---
- hosts: all
  vars:
    http_port: 22
    max_clients: 200
  remote_user: ec2-user
  pre_tasks:

  - name: Gathering ec2 facts
    action: ec2_facts
  - name: Instance De-register
    local_action:
      module: ec2_elb
      instance_id: i-00ece117361f814f8
      aws_region: us-east-1
      ec2_access_key: 
      ec2_secret_key: 
      state: absent

  tasks:

  - name: test connection
    ping:

  - name: ensure apache is at the latest version
    yum: name=httpd state=latest
    become: true
    notify:
    - restart apache

  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
    become: true

  - name: cancella vecchia pagina index
    file: path=/var/www/html/index.html state=absent force=yes
    become: true

  - name: copia nuova pagina dal repository github
    action: git repo=git://github.com/albruz/Ansible_index.git dest=/var/www/html version=HEAD force=yes
    become: true

  post_tasks:

  - name: Instance Register
    local_action:
      module: ec2_elb
      instance_id: i-00ece117361f814f8
      ec2_elbs: andrea-balancer
      state: present
      aws_region: us-east-1
      ec2_access_key: 
      ec2_secret_key: 

  handlers:
  - name: restart apache
    service: name=httpd state=restart
